# Generated by Django 2.1.7 on 2019-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='', max_length=80),
        ),
    ]
