# Generated by Django 2.1.7 on 2019-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190301_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Categoria do artigo', null=True, related_name='tag', to='news.Tag'),
        ),
    ]
