# Generated by Django 2.1.7 on 2019-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190301_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Categoria do artigo', related_name='tag', to='news.Tag'),
        ),
    ]
